---
backend_app_dir: "{{ project_root }}/backend"
backend_service_name: yolo-backend
backend_env_vars:
  PORT: "{{ backend_port }}"
  MONGODB_URI: "{{ mongodb_uri }}"
  NODE_ENV: "{{ app_environment }}"
  